import "./styles.css";

const app = document.querySelector<HTMLDivElement>("#app");

if (app) {
  app.innerHTML = `
    <main>
      <h1>__PROJECT_TITLE__</h1>
      <p>This project was generated by <code>web-boilerplate-generator</code>.</p>
    </main>
  `;
}
